const testData = [
	{
		titleName:'系统设置',
		key:'sub1',
		list:[
			{
				topName:'基本设置',
				path:'/dashboard/analysis',
				icon:'',
				key:'1'
			}
		]
	},
	{
		titleName:'任课教师成长档案管理',
		key:'sub2',
		list:[
			{
				topName:'任课老师信息',
				path:'/tArchivesManage/tMsg',
				icon:'',
				key:'2'
			},
			{
				topName:'培训经理管理',
				path:'/tArchivesManage/tgoThrough',
				icon:'',
				key:'3'
			},
			{
				topName:'获奖记录管理',
				path:'/tArchivesManage/tWinRecord',
				icon:'',
				key:'4'
			},
			{
				topName:'任课情况管理',
				path:'/tArchivesManage/situationManage',
				icon:'',
				key:'5'
			},
			{
				topName:'论文管理',
				path:'/tArchivesManage/paperManage',
				icon:'',
				key:'6'
			},
			{
				topName:'科研项目管理',
				path:'/tArchivesManage/researchProjectManage',
				icon:'',
				key:'7'
			},
		]
	},
	{
		titleName:'工作量管理',
		key:'sub3',
		list:[
			{
				topName:'工作量',
				path:'/workLoadManage/workLoad',
				icon:'',
				key:'8'
			}
		]
	},
	{
		titleName:'教学事故管理',
		key:'sub4',
		list:[
			{
				topName:'教学事故录入',
				path:'/teachingAccident/teachingAccidentInput',
				icon:'',
				key:'9'
			},
			{
				topName:'教学事故管理',
				path:'/teachingAccident/teachingAccidentManage',
				icon:'',
				key:'10'
			},
			{
				topName:'教学事故认定',
				path:'/teachingAccident/tAccidentCognizance',
				icon:'',
				key:'11'
			},
			{
				topName:'教学事故查询',
				path:'/teachingAccident/tAccidentCognizanceQuery',
				icon:'',
				key:'12'
			},
			{
				topName:'教学事故统计',
				path:'/teachingAccident/tAccidentCognizanceStatistics',
				icon:'',
				key:'13'
			}
		]
	},
	{
		titleName:'教职工考核管理',
		key:'sub5',
		list:[
			{
				topName:'考核设置',
				path:'/assessMange/assessSet',
				icon:'',
				key:'14'
			},
			{
				topName:'期初考核',
				path:'/assessMange/stageStar',
				icon:'',
				key:'15'
			},
			{
				topName:'期末考核',
				path:'/assessMange/stagsEnd',
				icon:'',
				key:'16'
			},
			{
				topName:'考核结果管理',
				path:'/assessMange/aResultMange',
				icon:'',
				key:'17'
			},
			{
				topName:'考核结果查询',
				path:'/assessMange/aResultMangeQuery',
				icon:'',
				key:'18'
			}
		]
	},
	{
		titleName:'教职工评价管理',
		key:'sub6',
		list:[
			{
				topName:'评价设置',
				path:'/tEvaluateMange/evaluateSet',
				icon:'',
				key:'19'
			},
			{
				topName:'发起评价',
				path:'/tEvaluateMange/startEvaluate',
				icon:'',
				key:'20'
			},
			{
				topName:'我的评价',
				path:'/tEvaluateMange/myEvaluate',
				icon:'',
				key:'21'
			},
			{
				topName:'评教查询',
				path:'/tEvaluateMange/evaluateQuery',
				icon:'',
				key:'22'
			},
			{
				topName:'评教统计',
				path:'/tEvaluateMange/evaluateStatistics',
				icon:'',
				key:'23'
			},
		]
	},
	{
		titleName:'年终总结管理',
		key:'sub7',
		list:[
			{
				topName:'填写总结',
				path:'/summaryManage/fillSummay',
				icon:'',
				key:'24'
			},
			{
				topName:'总结查询',
				path:'/summaryManage/findSummary',
				icon:'',
				key:'25'
			},
		]
	},
	{
		titleName:'教职工年终考核管理',
		key:'sub8',
		list:[
			{
				topName:'开始年终考核',
				path:'/assessmentManage/startAssessment',
				icon:'',
				key:'26'
			},
			{
				topName:'年终考核管理',
				path:'/assessmentManage/manageAssessment',
				icon:'',
				key:'27'
			},
			{
				topName:'年终考核统计',
				path:'',
				icon:'',
				key:'28'
			},
			{
				topName:'年终考核查询',
				path:'/assessmentManage/findAssessment',
				icon:'',
				key:'29'
			},
			{
				topName:'年终考核结果',
				path:'/assessmentManage/resultAssessment',
				icon:'',
				key:'30'
			},
		]
	},
]

export{
	testData
}